name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest-ubuntu:
    name: Tests (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install pytest
          pip install qsharp==1.12.1
      - name: Run tests
        run: pytest